### PR TITLE
prepare script for submission to PyPi

### PR DESCRIPTION
**Pull request by robertpeteuil**
### Files added:
- setup.py - instructs python how to install the script as a package
- LICENSE.txt - includes contents of MIT license
  - replace the contents with whatever license you want
- manifest.in - instructs python to include the license file in the package
- termigraph/__init__.py - necessary for building package

### File changed:
- moved termgraph.py to termgraph/termgraph.py - necessary for building package
- in termgraph.py - adjusted main() so it is directly callable

## preperation

Review `setup.py` and change and adjust any value you wish, particularly:
- version
- your name
- possibly add an `author_email` field
- license
- description
- keywords

Review `LICENSE.txt`
- Make sure its the license type you want
- change your name after the copyright statement in line 3

## create distribution files
- create an account on [PyPi](https://pypi.org/)
- update `setuptools`, `wheel` and `twine`
  - `pip3 install -U setuptools` (and so likewise for `wheel` & `twine`)
- build the source distribution: `python3 setup.py sdist`
- build the wheel for python 3: `python3 setup.py bdist_wheel`

## local test before submission
You now have build files, but before submitting them, you can perform a local test install
- cd into the "dist" folder and run: `pip install termgraph-0.1.0-py3-none-any.whl`
- this will install `termgraph` on your computer using the wheel generated by `setup.py` and link it to your path.
  - run this version by typing "termgraph" (no .py needed)
- Once you've verified that it works, you can uninstall it by typing "pip3 uninstall termgraph"

## submitting to PyPi
Once you're ready to submit it to PyPi, and you've changed the values in `setup.py`
- build the source distribution: `python3 setup.py sdist`
- build the wheel for python 3: `python3 setup.py bdist_wheel`
- the first time you submit it to PyPi
  - register the source code:  `twine register dist/termgraph-0.1.0.tar.gz` (Substitute your version #)
  - register the wheel: `twine register dist/termgraph-0.1.0-py3-none-any.whl`
- Upload the files to PyPi: `twine upload dist/*`

## Installing on local machine in [developer mode](https://pip.pypa.io/en/latest/reference/pip_install/#editable-installs)
Whenever you want to edit the script and see local changes immediately (without reinstalling each time), you can install the package in developer mode.
- First, make sure the package isn't already installed with pip
  - run `pip3 uninstall termgraph`
- `cd` into the directory containing `setup.py`
- type `pip3 install -e .`

## Publishing new Releases to PyPi
- change the version # in `setup.py`
- run the commands to generated updated distribution & wheel files
  - the version number in the files will change
- upload the new versions
  - make sure to delete the old tar & wheel files from the "dist" directory

### CODE REVIEW

**Comment by bhrutledge** [comment]
Just stumbled upon this project via the [Import Python newsletter](https://importpython.com/newsletter/). Very cool, but my first thought was "it'd be nice if you could `pip install` it." Lo and behold, this awesome PR already exists! Nicely done.

One suggestion for this PR: update `readme.md` to be `README.md`, with instructions that reflect the `pip` installation and `termgraph` entry point.

**Comment by robertpeteuil** [comment]
@bhrutledge Thanks for noticing the PR and for the suggestion about the readme

Your suggestions are spot on.  I'm going to see if @mkaz has any questions, feedback or suggestions before changing anything else.

@mkaz - congrats on getting list in the [Import Python newsletter](https://importpython.com/newsletter/)!  
- That will likely generate some traffic, and is probably a good reason to submit it to PyPi
- You can merge this PR 
- Then before you submit it, I can submit the README adjustments (or you to them) 

 Let me know if you have any questions, comments or concerns.

**Comment by mkaz** [comment]
@robertpeteuil  Thanks for submitting this PR, I appreciate the work and detailed instructions. It might be a day or two before I can address the items.

Pretty exciting to get featured elsewhere too :-)

**Comment by mkaz** [comment]
Actually, I've got some time this morning and your instructions have been so good that I think I've got it worked out. I'll be able to rebase and merge this PR and submit.

**Comment by robertpeteuil** [comment]
Cool. I'll be around the morning. Let me know if you have any questions.

**Comment by mkaz** [comment]
I think I got it submitted properly to PyPI and merged your PR - take a look and see if you can install, it worked well for me.

Again, thanks so much for the detailed and clear instructions.

Just an FYI, a minor update in your instructions, the register step is no longer needed. The utility prompts you to just upload dist/* and pre-registration is not needed. It was still straight-forward.

**Comment by robertpeteuil** [comment]
Awesome.  It's up there - you can see if [here](https://pypi.org/project/termgraph/).

You may want to update the readme:
- replace `termgraph.py` with just `termgraph`(as its nwo invoked)
- update the installation instructions
  - remove the section on installing pre-reqs (no longer necessary)
  - add a line to "install with pip" `pip3 install termgraph`
- I noticed the pictures aren't displaying properly on the PyPi site, they made need fully qualified URLs

Once you've upgraded the read me, just bump the version # in setup.py, rebuild the packages, and resubmit.

**Comment by robertpeteuil** [comment]
A quick update, i just figured out how to correct the display of the bottom three images in your readme when viewed on PyPi.  

Unfortunately, I cannot fix it for you, as it requires copying the images to an issue in your repository.

## Problem:
- The bottom three pictures use local URL references to files on GitHub. ex: "docs/img/example2.png"
- This breaks when rendered on PyPi, since they're not fully qualified URLs

## Free & Easy Fix
- You can create fully qualified URLs for pictures by copying them to an "issue" in your repository.  
- Open an issue called "Images", and drag & drop the images into the issue description.
  - when you "drop" an image, it will be immediately replaced with a URL.  
  - Copy that URL, and place it in your README in the `src` references for those pictures.
- repeat for other images, copying & placing each in the readme
- when finished close the issue (but don't delete it).  It's still there, and you can add & change the photos later.
- An added benefit is that you don't have example photos littering your repository.

Let me know if you have any questions.

**Pull request merged**
