### PR TITLE
PEP8, Code Styles, and Pylint

### LINKED ISSUE #30: PEP8 and other issues
The code currently does not follow [PEP8](https://www.python.org/dev/peps/pep-00080). By following the style guide, the code would be more readable, consistency would be better and it would be easier to maintain.

When I run `pylint` on `termgraph.py`, it outputs a large amount of warnings:
- Spaces before and after `()` and `[]`, i.e. `parser.add_argument( '--title', help='Title of graph' )` should be `parser.add_argument('--title', help='Title of graph')`
- Lines too long (should be 79 chars at maximum)
- Lots of unused imports from wildcard imports (wildcard imports should be avoided)
- Import order is wrong

It might also be better to use classes and a more object-oriented approach. This would make it more organized, easier to build upon and easier to re-use in other projects. Although this might better be filed as a new issue.

### PR DESCRIPTION
**Pull request by mkaz**
This PR addresses various code style issues to match PEP8 as close as possible, as uncovered by pylint.

Fixes #30

### CODE REVIEW

**Comment by nnist** [comment]
This looks good, it seems to fix all the whitespace problems. All lines are under 100 chars, which is fine really.

There are a few more issues left:

1. Some function names don't conform to snake_case naming style. An example would be
    ```py
    def findMin(a):
        return min([b[-1] for b in a])
    ```
    which should be
    ```py
    def find_min(a):
        return min([b[-1] for b in a])
    ```

2. Another issue is the wildcard imports. Only the necessary modules should be imported.
3. Some other minor things, such as one-char variables.

I could create a new pull request which would fix these things, if you'd like. I enjoy doing this kind of clean-up work!

**Comment by mkaz** [comment]
@nnist that would be great if you want to continue on this PR!
It was still progress for me, I just wanted to push it up so work wouldn't get lost.

**Comment by mkaz** [comment]
@nnist that would be great if you want to continue on this PR!
It was still progress for me, I just wanted to push it up so work wouldn't get lost.

**Comment by nnist** [comment]
Alright! I'll get started asap.

**Comment by nnist** [comment]
Done! I created a new pull request for this, #35.

This pull request (#33) can be closed now, I think.

**Pull request merged**
